version: 2.1

workflows:
  test:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test
